Castle Center - Elevator:
    Marble Gallery - Elevator Room:
        Activate Elevator:
            - None
Castle Keep - Teleporter:
    Reverse Keep - Teleporter:
        Activate Warp:
            - None
Prologue:
    Castle Entrance - Main Path:
        Richter defeats Dracula:
            - None
Reverse Keep - Teleporter:
    Castle Keep - Teleporter:
        Activate Warp:
            - None
Marble Gallery - Elevator Room:
    Castle Center - Elevator:
        Activate Elevator:
            - None
Reverse Warp Room:
    Loading Room - Between Cave and Reverse Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Cave
    Loading Room - Between Death Wing's Lair and Reverse Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Death Wing's Lair
    Loading Room - Between Reverse Entrance and Reverse Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Reverse Entrance
    Loading Room - Between Reverse Keep and Reverse Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Reverse Keep
    Loading Room - Between Reverse Outer Wall and Reverse Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Reverse Outer Wall
Start New Game:
    Axe Armor Mode:
        Axe Armor Mode:
            - Knowledge - How to Access Axe Armor Mode
    Luck Mode:
        Luck Mode:
            - Knowledge - How to Access Luck Mode
    Normal Mode:
        Normal Mode:
            - None
    Richter Mode:
        Richter Mode:
            - Knowledge - How to Access Richter Mode
Axe Armor Mode:
    Prologue:
        Start Game:
            - None
Luck Mode:
    Prologue:
        Start Game:
            - None
Normal Mode:
    Prologue:
        Start Game:
            - None
Richter Mode:
    Castle Entrance - Main Path:
        Start Game:
            - None
Teleport to Long Library:
    Long Library - Outside Shop:
        Basic Movement:
            - None
Warp Room:
    Loading Room - Between Castle Entrance and Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Castle Entrance
    Loading Room - Between Abandoned Mine and Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Abandoned Mine
    Loading Room - Between Castle Keep and Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Castle Keep
    Loading Room - Between Olrox's Quarters and Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Olrox's Quarters
    Loading Room - Between Outer Wall and Warp Room:
        Activate Warp:
            - Progression - Unlock Warp to Outer Wall