---
Options:
    Assign Power of Wolf relic a unique ID: true
    Clock hands show minutes and seconds instead of hours and minutes: true
    Disable clipping on screen edge of Demon Switch Wall: true
    Shift wall in Plaque Room With Breakable Wall away from screen edge: true
    Disable clipping on screen edge of Snake Column Wall: true
    Disable clipping on screen edge of Tall Zig Zag Room Wall: true
    Enable debug mode: true
    Normalize room connections: true
    Shuffle Pitch Black Spike Maze: true
    Skip Maria cutscene in Alchemy Laboratory: true
Quest shuffler:
    Shuffle quest rewards: true
Stage shuffler:
    Shuffle connections between stages: true
    Loading room labels: Stage
