---
Options:
    Assign Power of Wolf relic a unique ID: true
    Clock hands show minutes and seconds instead of hours and minutes: true
    Color-code each stage on the map: true
    Disable clipping on screen edge of Demon Switch Wall: true
    Disable clipping on screen edge of Left Gear Room Wall: true
    Disable clipping on screen edge of Pendulum Room Wall: true
    Disable clipping on screen edge of Snake Column Wall: true
    Disable clipping on screen edge of Tall Zig Zag Room Wall: true
    Enable debug mode: false
    Normalize room connections: true
    Normalize Ferryman Gate: true
    Preserve unsaved map data: Revelation
    Shift wall in Plaque Room With Breakable Wall away from screen edge: true
    Shuffle Pitch Black Spike Maze: true
    Skip Maria cutscene in Alchemy Laboratory: true
Quest shuffler:
    Item pool: Vanilla
    Relic pool: Vanilla
    Shuffle enemy drops: true
    Shuffle items: true
    Shuffle special items: true
    Shuffle relics: true
Room shuffler:
    Shuffle rooms within stages: true
Stage shuffler:
    Shuffle connections between stages: true
    Loading room labels: Connection
