
Action - Collect Item at Outer Wall Garnet Location:
    Outcomes:
        Item - Garnet: 1
        Progression - Item at Outer Wall Garnet Location Collected: true
    Requirements:
        Corner Mist:
            Knowledge - How to Perform Corner Mist: true
            Location: Outer Wall, Gallery Side
            Progression - Item at Outer Wall Garnet Location Collected: false
            Progression - Mist Transformation: true
        Double Jump:
            Location: Outer Wall, Gallery Side
            Progression - Item at Outer Wall Garnet Location Collected: false
            Progression - Double Jump: true
        Flight - Bat Form:
            Location: Outer Wall, Gallery Side
            Progression - Item at Outer Wall Garnet Location Collected: false
            Progression - Bat Transformation: true
        Flight - Powered Mist:
            Location: Outer Wall, Gallery Side
            Progression - Item at Outer Wall Garnet Location Collected: false
            Progression - Longer Mist Duration: true
            Progression - Mist Transformation: true
        Gravity Jump:
            Location: Outer Wall, Gallery Side
            Progression - Item at Outer Wall Garnet Location Collected: false
            Progression - Gravity Jump: true
        Wolf Slope Jump:
            Knowledge - How to Perform a Wolf Slope Jump: true
            Location: Outer Wall, Gallery Side
            Progression - Item at Outer Wall Garnet Location Collected: false
            Progression - Wolf Transformation: true
        Wolf-Mist Rise:
            Execution - Wolf-Mist Rise: true
            Location: Outer Wall, Gallery Side
            Progression - Item at Outer Wall Garnet Location Collected: false
            Progression - Mist Transformation: true
            Progression - Wolf Transformation: true
Action - Start Game in Luck Mode:
    Outcomes:
        Character: Richter
        Game Mode: Luck
        Location: Prologue
    Requirements:
        DEFAULT:
            Location: Name Entry Screen
            Knowledge - How to Enable Luck Mode: true
            Rules - Luck Mode Allowed: true
Action - Start Game in Normal Mode:
    Outcomes:
        Character: Richter
        Game Mode: Normal
        Location: Prologue
    Requirements:
        DEFAULT:
            Location: Name Entry Screen
Action - Use Library Card:
    Outcomes:
        Location: Long Library, Outside Shop
        Item - Library Card: -1
    Requirements:
        DEFAULT:
            Character: Alucard
            Item - Library Card:
                Minimum: 1
Action - Use Library Card with Duplicator:
    Outcomes:
        Location: Long Library, Outside Shop
    Requirements:
        DEFAULT:
            Character: Alucard
            Item - Library Card:
                Minimum: 1
            Item - Duplicator:
                Minimum: 1
Action - Acquire Heart Refresh in Prologue:
    Outcomes:
        Item - Heart Refresh: 1
        Progression - Heart Refresh in Prologue Acquired: true
    Requirements:
        DEFAULT:
            Location: Prologue
            Progression - Heart Refresh in Prologue Acquired: false
            Knowledge - How to Acquire Heart Refresh in Prologue: true
Action - Acquire Neutron Bomb in Prologue:
    Outcomes:
        Item - Neutron Bomb: 1
        Progression - Neutron Bomb in Prologue Acquired: true
    Requirements:
        DEFAULT:
            Location: Prologue
            Progression - Neutron Bomb in Prologue Acquired: false
            Knowledge - How to Acquire Neutron Bomb in Prologue: true
Action - Defeat Dracula in Prologue as Richter:
    Outcomes:
        Character: Alucard
        Location: Castle Entrance, After Drawbridge
        Item - Alucard Shield: 1
        Item - Alucard Sword: 1
        Item - Dragon Helm: 1
    Requirements:
        DEFAULT:
          Location: Prologue
          Progression - Dracula Defeated: false
Movement - Long Library, Soul of Bat Room:
    Outcomes:
        Location: Long Library, Soul of Bat Room
    Requirements:
        DEFAULT:
            Location: Long Library, Basement
            Progression - Mist Transformation: true
        Perform Shift Line Using Double Heart Refresh:
            Location: Long Library, Back Section
            Item - Heart Refresh:
                Minimum: 2
            Item - Duplicator:
                Minimum: 1
            Knowledge - How to Perform Shift Line Using Double Heart Refresh: true
            Rules - Shift Line Glitches Allowed: true
Movement - Loading Room, Between Alchemy Laboratory and Castle Entrance:
    Outcomes:
        Location: Loading Room, Between Alchemy Laboratory and Castle Entrance
    Requirements:
        Alchemy Laboratory:
            Location: Alchemy Laboratory, DEFAULT
        Castle Entrance:
            Location: Castle Entrance, Cube of Zoe Room